// const ApiRootUrl = 'https://localhost:8802/';
const ApiRootUrl = 'https://www.yqtech.ltd:8802/';
const ApiRootUrlWeb = 'https://www.yqtech.ltd:8806/';
// const ApiRootUrl = 'https://192.168.1.94:8802/';

module.exports = {
  GettaskbyType: ApiRootUrl + 'gettaskbyTypeXiaoyuan', //获取首页帖子
  GetBanner: ApiRootUrl + 'getBannerQuanzi', //获取首页banner
  AddTask: ApiRootUrl + 'addtaskQuanzi', // 发布帖子
  AddRank: ApiRootUrl + 'addRankQuanzi', // 合成北理工 提交成绩
  GetRank: ApiRootUrl + 'getRankListQuanzi', // 合成北理工 排名
  Login: ApiRootUrl + 'wxLoginQuanzi',
  MsgCheck:ApiRootUrl + 'msgCheckQuanzi',
  ImgCheck:ApiRootUrl + 'imgCheckCaicai',
  AddLike:ApiRootUrl + 'addlikeQuanzi',
  IncLike: ApiRootUrl + 'incLikeQuanzi',
  DecLike: ApiRootUrl + 'decLikeQuanzi',
  GetlikeByPk: ApiRootUrl + 'getlikeByPkQuanzi',
  DeleteLike: ApiRootUrl + 'deleteLikeQuanzi',
  Addcomment: ApiRootUrl + 'addcommentQuanzi',
  GetMember: ApiRootUrl + 'getMemberQuanzi',
  GettaskbyId: ApiRootUrl + 'gettaskbyIdXiaoyuan',
  DeleteTask: ApiRootUrl + 'deleteTaskQuanzi',
  DeleteComment: ApiRootUrl + 'deleteCommentQuanzi',
  GetSecondLevel: ApiRootUrl + 'getSecondLevelQuanzi',
  GetCommentByType: ApiRootUrl + 'getCommentByTypeXiaoyuan',
  IncCommentLike: ApiRootUrl + 'incCommentLikeQuanzi',
  DecCommentLike: ApiRootUrl + 'decCommentLikeQuanzi',
  GettaskbySearch: ApiRootUrl + 'gettaskbySearchXiaoyuan',
  GetlikeByOpenid: ApiRootUrl + 'getlikeByOpenidQuanzi',
  GettaskbyOpenid: ApiRootUrl + 'gettaskbyOpenIdQuanzi',
  GetCommentByApplyto: ApiRootUrl + 'getCommentByApplytoQuanzi',
  GetCommentByOpenid: ApiRootUrl + 'getCommentByOpenidQuanzi',
  SendComment:ApiRootUrl + 'sendCommentQuanzi',
  AddVerifyUserQuanzi:ApiRootUrl + 'addVerifyUserQuanzi',
  GetQRList:ApiRootUrl + 'getQRList',
  SendEmailBeita:ApiRootUrl + 'sendEmailBeita',
  CheckVerifyUserQuanzi:ApiRootUrl + 'checkVerifyUserQuanzi',
  CheckEmailQuanzi:ApiRootUrl + 'checkEmailQuanzi',
  GetLatestFriendMsgList:ApiRootUrl + 'getLatestFriendMsgList',
  AddUserPMRequest:ApiRootUrl + 'addUserPMRequest',
  ConnectSocket:ApiRootUrl.replace('https','wss') + 'imserver/',
  GetUsersChatDetail:ApiRootUrl + 'getUsersChatDetail',
  UdpateUserInfoXiaoyuan:ApiRootUrl + 'udpateUserInfoXiaoyuan',
  UpdateUserPMRequestStatus:ApiRootUrl + 'updateUserPMRequestStatus',
  StopUserPM:ApiRootUrl + 'stopUserPM',
  UpdateLastReadTime:ApiRootUrl + 'updateLastReadTime',
  GetDailySummary:ApiRootUrl + 'getDailySummary',
  GetHotTaskXiaoyuan:ApiRootUrl + 'getHotTaskXiaoyuan',
  SendPMNotifXiaoyuan:ApiRootUrl + 'sendPMNotifXiaoyuan',
  AddBlacklistXiaoyuan:ApiRootUrl + 'addBlacklistXiaoyuan',
  GenerateSelectedXiaoyuan:ApiRootUrl + 'generateSelectedXiaoyuan',
  TopTaskXiaoyuan:ApiRootUrl + 'topTaskXiaoyuan',
  DownTaskXiaoyuan:ApiRootUrl + 'downTaskXiaoyuan',
  GetPhoneXiaoyuan: ApiRootUrl + 'getPhoneXiaoyuan', 
  CheckUserPhoneXiaoyuan: ApiRootUrl + 'checkUserPhoneXiaoyuan', 
  //20240324
  AddMeetupXiaoyuan: ApiRootUrl + 'addMeetupXiaoyuan', 
  //20240329
  GetAllMeetupXiaoyuan: ApiRootUrl + 'getAllMeetupXiaoyuan', 
  GetAllMeetupByCategoryXiaoyuan: ApiRootUrl + 'getAllMeetupByCategoryXiaoyuan', 
  JoinMeetupXiaoyuan: ApiRootUrl + 'joinMeetupXiaoyuan', 
  DeleteMeetupXiaoyuan: ApiRootUrl + 'deleteMeetupXiaoyuan', 
  LeaveMeetupXiaoyuan: ApiRootUrl + 'leaveMeetupXiaoyuan', 
  GetAllGroupBuyXiaoyuan:ApiRootUrl + 'getAllGroupBuyXiaoyuan', 
  GetGroupBuyByIdXiaoyuan:ApiRootUrl + 'getGroupBuyByIdXiaoyuan', 
  //20241016
  SetCampusRegion:ApiRootUrl + 'setCampusRegion', 
  GetUserInfo:ApiRootUrl + 'getUserInfo', 
  //paotui
  AddUserInfo: ApiRootUrl + 'addUserInfo', 
  GetRiderByOpenid: ApiRootUrl + 'getRiderByOpenid',
  AddTaskPaotui:ApiRootUrl + 'addTask',
  GetAllTaskPaotui: ApiRootUrl + 'getAllTaskPaotui',
  GetTaskbyStatus: ApiRootUrl + 'getTaskbyStatus',
  GetTaskByReleaseOpenId: ApiRootUrl + 'getTaskbyReleaseOpenId', 
  GetTaskByPickupOpenId: ApiRootUrl + 'getTaskbyPickupOpenId', 
  GetTaskById: ApiRootUrl + 'getTaskbyId', 
  RiderPickupSub: ApiRootUrl + 'riderPickupSub',
  UserPickupOrder: ApiRootUrl + 'userPickupOrder', 
  RiderCompleteSub: ApiRootUrl + 'riderCompleteSub',
  OrderCompleteByRider: ApiRootUrl + 'orderCompleteByRider', 
  OrderComplete: ApiRootUrl + 'orderComplete', 
  PayTask: ApiRootUrl + 'payTask', 
  NewTaskSub: ApiRootUrl + 'newTaskSub',
  CancelTask: ApiRootUrl + 'cancelTask', 
  GetProfile: ApiRootUrl + 'getProfile',
  OrderCompleteSub: ApiRootUrl + 'orderCompleteSub',
  PaySuccess: ApiRootUrl + 'paySuccess',
  SendEmailCode: ApiRootUrl + 'sendEmailXiaoyuan',
  SetIdentityXiaoyuan: ApiRootUrl + 'setIdentityXiaoyuan',
  //20250711
  AddGroupBuyRecordXiaoyuan: ApiRootUrl + 'addGroupBuyRecordXiaoyuan',
  //20250815
  RiderWithdrawal: ApiRootUrl + 'riderWithdrawal',
  RiderWithdrawalComplete: ApiRootUrl + 'riderWithdrawalComplete',
  // score 模块
  ScoreCreateTopic: ApiRootUrl + 'score/createTopic',
  ScoreUpdateTopic: ApiRootUrl + 'score/updateTopic',
  ScoreListTopics: ApiRootUrl + 'score/listTopics',
  ScoreGetTopic: ApiRootUrl + 'score/getTopic',
  ScoreListOptions: ApiRootUrl + 'score/listOptions',
  ScoreAddOption: ApiRootUrl + 'score/addOption',
  ScoreUpdateOption: ApiRootUrl + 'score/updateOption',
  ScoreToggleOption: ApiRootUrl + 'score/toggleOption',
  ScoreVoteOption: ApiRootUrl + 'score/voteOption',
  ScoreListVotes: ApiRootUrl + 'score/listVotes',
};